<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSymptomSheetsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('symptom_sheets', function (Blueprint $table) {
            $table->increments('id');
            $table->string('fibromyalgia',1);
            $table->string('gout',1);
            $table->string('graves',1);
            $table->string('hemorrhoids',1);
            $table->string('hyperkinesis',1);
            $table->string('hyperthyroidism',1);
            $table->string('hypoglycemia',1);
            $table->string('hypothyroidism',1);
            $table->string('headachesmigraine',1);
            $table->string('headachessinus',1);
            $table->string('headachestension',1);
            $table->string('inflammation',1);
            $table->string('fissuresanal',1);
            $table->string('fistulas',1);
            $table->string('gallstones',1);
            $table->string('ulcer',1);
            $table->string('learningdisability',1);
            $table->string('lyme',1);
            $table->string('mentalretardation',1);
            $table->string('menieresdisease',1);
            $table->string('multiplesclerosis',1);
            $table->string('neuritis',1);
            $table->string('neuropathy',1);
            $table->string('parkinsonsdisease',1);
            $table->string('psoriasis',1);
            $table->string('schizophrenia',1);
            $table->string('scleroderma',1);
            $table->string('smoking',1);
            $table->string('bursitis',1);
            $table->string('fractures',1);
            $table->string('jointpain',1);
            $table->string('jointstiffness',1);
            $table->string('osteoporosis',1);
            $table->string('musclecramps',1);
            $table->string('musclepain',1);
            $table->string('muscleweakness',1);
            $table->string('cantskipmeals',1);
            $table->string('cravefats',1);
            $table->string('cravesaltyfoods',1);
            $table->string('cravestarches',1);
            $table->string('cravesweets',1);
            $table->string('hungerexcessive',1);
            $table->string('hungernoappetite',1);
            $table->string('irritablebeforemeals',1);
            $table->string('sugarreactions',1);
            $table->string('tendtogainweight',1);
            $table->string('tendtoloseweight',1);
            $table->string('allergiesdairy',1);
            $table->string('allergieseggs',1);
            $table->string('allergiesfish',1);
            $table->string('allergieschemical',1);
            $table->string('allergiesmold',1);
            $table->string('allergiesseasonal',1);
            $table->string('angina',1);
            $table->string('arteriosclerosis',1);
            $table->string('bloodpressurehigh',1);
            $table->string('bloodpressurelow',1);
            $table->string('cholesterolhigh',1);
            $table->string('dizziness',1);
            $table->string('easybruising',1);
            $table->string('heartbeatsskip',1);
            $table->string('heartpalpitations',1);
            $table->string('heartraterapid',1);
            $table->string('poorcirculation',1);
            $table->string('triglycerideshigh',1);
            $table->string('cough',1);
            $table->string('postnasaldrip',1);
            $table->string('sinuscongestion',1);
            $table->string('bodytemperaturelow',1);
            $table->string('bodytemperaturecoldinwinter',1);
            $table->string('dryskin',1);
            $table->string('acne',1);
            $table->string('infectionsbladder',1);
            $table->string('infectionskidney',1);
            $table->string('infectionsfungalcandida',1);
            $table->string('infectionsfungalyeast',1);
            $table->string('infectionsviruses',1);
            $table->string('hairloss',1);
            $table->string('hives',1);
            $table->string('slowwoundhealing',1);
            $table->string('excessiveplaqueonteeth',1);
            $table->string('gumdisease',1);
            $table->string('toothdecayfrequentcavities',1);
            $table->string('anger',1);
            $table->string('brainfog',1);
            $table->string('confusion',1);
            $table->string('irritability',1);
            $table->string('mindraces',1);
            $table->string('moodswings',1);
            $table->string('obsessivecompulsive',1);
            $table->string('panicattacks',1);
            $table->string('poormemory',1);
            $table->string('fatigue',1);
            $table->string('troublesleeping',1);
            $table->string('seizures',1);
            $table->string('kidneystones',1);
            $table->string('urinationfrequent',1);
            $table->string('urinationpainful',1);
            $table->string('waterretention',1);
            $table->string('impotence',1);
            $table->string('prostateproblems',1);
            $table->string('cramps',1);
            $table->string('periodsheavy',1);
            $table->string('periodsirregular',1);
            $table->string('periodslight',1);
            $table->string('premenstrualsyndrome',1);
            $table->string('menstruationdelayedstopped',1);
            $table->string('menopause',1);
            $table->string('cystsovarian',1);
            $table->string('papsmearabnormal',1);
            $table->string('breastsfibrocystic',1);
            $table->string('breaststumors',1);
            $table->string('infertility',1);
            $table->string('vaginalyeastinfections',1);
            $table->string('hotflashes',1);
            $table->string('sensitivetoheat',1);
            $table->string('sensitivetocaffeine',1);
            $table->string('alcoholism',1);
            $table->string('anemia',1);
            $table->string('anxiety',1);
            $table->string('osteoarthritis',1);
            $table->string('rheumatoidarthritis',1);
            $table->string('asthma',1);
            $table->string('autism',1);
            $table->string('adhd',1);
            $table->string('bipolar',1);
            $table->string('bloating',1);
            $table->string('bronchitis',1);
            $table->string('chronicfatigue',1);
            $table->string('cirrhosis',1);
            $table->string('colitis',1);
            $table->string('constipationoccasional',1);
            $table->string('constipationongoing',1);
            $table->string('diarrheaoccasional',1);
            $table->string('diarrheaongoing',1);
            $table->string('gas',1);
            $table->string('stomachpain',1);
            $table->string('delayeddevelopment',1);
            $table->string('depression',1);
            $table->string('diabetes1',1);
            $table->string('diabetes2',1);
            $table->string('diabetes3',1);
            $table->string('diverticulitis',1);
            $table->string('drugaddiction',1);
            $table->string('dyslexia',1);
            $table->string('eczema',1);
            $table->string('emphysema',1);
            $table->string('cataracts',1);
            $table->string('glaucoma',1);
            $table->string('heartattack',1);
            $table->string('tumoractive',1);
            $table->string('tumorbenign',1);
            $table->string('tumorcancer',1);
            $table->string('tumorfatty',1);
            $table->string('tinnitus',1);
            $table->string('ringinginears',1);            
            $table->integer('client_id')->references('id')->on('clients');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('symptom_sheets');
    }
}
